# Generated by Django 5.1.1 on 2024-10-11 06:55

import django.core.validators
import django.db.models.deletion
import school.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emis_number', models.CharField(max_length=100)),
                ('center_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=10)),
                ('badge', models.ImageField(blank=True, null=True, upload_to='badge/')),
                ('lname', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('nin', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('created', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='badge/')),
                ('gfname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('glname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('gemail', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('gphone', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('gnin', models.CharField(default='', max_length=20)),
                ('gdate_of_birth', models.DateField()),
                ('ggender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('gphoto', models.ImageField(blank=True, null=True, upload_to='badge/')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.region')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fname', models.CharField(max_length=255)),
                ('mname', models.CharField(blank=True, max_length=255, null=True)),
                ('lname', models.CharField(max_length=255)),
                ('lin', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('index_number', models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[school.models.validate_index_number])),
                ('date_of_birth', models.DateField()),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=10)),
                ('physic', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Special Needs', 'Special Needs')], default='Normal', max_length=25, null=True)),
                ('nationality', models.CharField(choices=[('National', 'National'), ('Foreigner', 'Foreigner')], default='National', max_length=25)),
                ('refugee', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25, null=True)),
                ('sponsorship', models.CharField(blank=True, choices=[('School sponsored', 'School sponsored'), ('Parent sponsored', 'Parent sponsored')], max_length=25, null=True)),
                ('photo', models.ImageField(upload_to='athlete_photos/')),
                ('ple_certificate', models.FileField(blank=True, null=True, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('uce_certificate', models.FileField(blank=True, null=True, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('student_pass', models.FileField(blank=True, null=True, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('student_visa', models.FileField(blank=True, null=True, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('bursary', models.FileField(blank=True, null=True, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('student_pass_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('uneb_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('uneb_eq_results', models.FileField(blank=True, null=True, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('refugee_card', models.FileField(blank=True, null=True, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('Parent_fname', models.CharField(max_length=100)),
                ('Parent_lname', models.CharField(max_length=100)),
                ('parent_phone_number', models.CharField(max_length=15)),
                ('parent_nin', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Other', 'Other')], max_length=15)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport', to='accounts.sport')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom', to='school.classroom')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='school_official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('lname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('nin', models.CharField(default='', max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('role', models.CharField(blank=True, choices=[('Coach', 'Coach'), ('Teacher', 'Teacher'), ('Assistant Games Teacher', 'Assistant Games Teacher'), ('Assistant Head Teacher', 'Assistant Head Teacher'), ('Nurse', 'Nurse'), ('Doctor', 'Doctor'), ('District Education Officer', 'District Education Officer'), ('District Sports Officer', 'District Sports Officer')], max_length=40, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='badge/')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='school.school')),
            ],
        ),
    ]
