# Generated by Django 5.1.1 on 2024-11-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='center_number',
            field=models.CharField(max_length=100),
        ),
    ]
