# Generated by Django 5.1.1 on 2024-09-20 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='physic',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Special Needs', 'Special Needs')], default='Normal', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
