# Generated by Django 5.1.1 on 2024-11-15 14:29

import school.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_school_center_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='uce_index_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[school.models.validate_index_number]),
        ),
        migrations.AddField(
            model_name='school_official',
            name='residence',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
