# Generated by Django 5.1.1 on 2024-09-21 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_school_physic_athlete_physic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='nationality',
            field=models.CharField(choices=[('National', 'National'), ('Foreigner', 'Foreigner')], default='National', max_length=25),
        ),
        migrations.AddField(
            model_name='athlete',
            name='refugee',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='refugee_card',
            field=models.ImageField(default=1, upload_to='athlete_photos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athlete',
            name='student_pass',
            field=models.ImageField(default=1, upload_to='athlete_photos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='athlete',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to='school.school'),
        ),
        migrations.AlterField(
            model_name='school',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='school_official',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='school.school'),
        ),
    ]
