# Generated by Django 5.1.1 on 2024-11-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_athlete_uce_index_number_school_official_residence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='uce_index_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
