# Generated by Django 5.1.1 on 2024-11-16 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('school', '0004_alter_athlete_uce_index_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport', to='accounts.sport'),
        ),
    ]
