# Generated by Django 5.1.1 on 2024-09-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_athlete_index_number_alter_athlete_lin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='athlete_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
