# Generated by Django 5.1.1 on 2024-09-26 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_athlete_athlete_id_athlete_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='ple_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='refugee_card',
            field=models.FileField(blank=True, null=True, upload_to='athlete_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='student_pass',
            field=models.FileField(blank=True, null=True, upload_to='athlete_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='uce_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
