# Generated by Django 5.1.1 on 2024-10-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_athlete_student_pass_code_athlete_uneb_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
