# Generated by Django 5.1.1 on 2024-11-15 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='agm_photo/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('school', models.CharField(max_length=125)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=14)),
                ('position', models.CharField(blank=True, choices=[('President ', 'President '), ('Vice President 1', 'Vice President 1'), ('Vice President 2', 'Vice President 2'), ('Vice President 3', 'Vice President 3'), ('CEO', 'CEO'), ('Chairperson', 'Chairperson'), ('Vice Chairperson', 'Vice Chairperson'), ('General Secretary', 'General Secretary'), ('ASSHU Representative', 'ASSHU Representative'), ('Assistant General Secretary', 'Assistant General Secretary'), ('Treasurer', 'Treasurer'), ('Secretary for Women', 'Secretary for Women'), ('Western Representative', 'Western Representative'), ('Eastern Representative', 'Eastern Representative'), ('Northern Representative', 'Northern Representative'), ('Central Representative', 'Central Representative'), ('Kampala Representative', 'Kampala Representative'), ('Committee Member', 'Committee Member')], max_length=44, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district', to='accounts.district')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agm_region', to='accounts.region')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agm_zone', to='accounts.zone')),
            ],
        ),
    ]
