# Generated by Django 5.1.1 on 2024-11-04 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('agm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegates',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='delegates',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agm_zone', to='accounts.zone'),
            preserve_default=False,
        ),
    ]
