# Generated by Django 5.1.1 on 2024-11-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agm', '0002_delegates_email_alter_delegates_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegates',
            name='position',
            field=models.CharField(blank=True, choices=[('Chairperson', 'Chairperson'), ('Vice Chairperson', 'Vice Chairperson'), ('General Secretary', 'General Secretary'), ('ASSHU Representative', 'ASSHU Representative'), ('Assistant General Secretary', 'Assistant General Secretary'), ('Treasurer', 'Treasurer'), ('Secretary for Women', 'Secretary for Women'), ('Western Representative', 'Western Representative'), ('Eastern Representative', 'Eastern Representative'), ('Northern Representative', 'Northern Representative'), ('Central Representative', 'Central Representative'), ('Kampala Representative', 'Kampala Representative'), ('Committee Member', 'Committee Member')], max_length=44, null=True),
        ),
    ]
