# Generated by Django 5.1.1 on 2024-10-01 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athleteenrollment',
            name='sport',
        ),
    ]
