# Generated by Django 5.1.1 on 2024-10-03 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_remove_athleteenrollment_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteenrollment',
            name='school_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_enrollments', to='enrollment.schoolenrollment'),
        ),
    ]
