from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *


urlpatterns = [
    path("addschool/", school_new, name="newschool"),
    path("school/<int:id>", school_detail, name="schooldetail"),
    path("updateschool/<int:id>", schoolupdate, name="schoolupdate"),
    path("delschool/<int:id>", DeleteSchool, name="delschool"),
    path("schools/", Schools, name="schools"),
    path('schools/data/', school_data_view, name='school_data'),
    path("users_data/", users_data, name="users_data"),
    # path("schools/", Schools, name="schools"),
    # path("updateofficial/<int:id>", OfficialDetail, name="updateofficial"),
    path("official/<int:id>", OfficialDetail, name="official"),
    path("export_csv/", export_csv, name="export_csv"),
    path("export_pdf/", exportp_csv, name="export_pdf"),
    # path("export_pdf/", exportp_csv, name="export_pdf"),
    path("newathlete/", newAthlete, name="add_athlete"),
    path("athletes/", athletes, name="athletes"),
    path("dathletes/", red_athletes, name="dathletes"),
    path("archives/", archives, name="archives"),
    path("allathletes/", all_athletes, name="allathletes"),
    path("athlete/<int:id>", AthleteDetail, name="athlete"),
    path("editathlete/<int:id>", AthleteUpdate, name="updateathlete"),
    path("delete-athlete/<int:id>", DeleteAthlete, name="del_athlete"),
    # path("delete-athlete/<int:id>", DeleteAthlete, name="del_athlete"),
    path('athletes/data/', athlete_data_view, name='athlete_data'),
    path('archives/data/', archives_data_view, name='archives_data'),
    # path('athletes/', all_athletes_page, name='all_athletes_page'),
    path("screens/", Screened, name="screened"),
    # path("export_pdf/", exportp_csv, name="export_pdf"),
    path('export_pcsv/', export_pcsv, name='export_pcsv'),
    path('export-scsv/', export_scsv, name='export_scsv'),
    path("payments/<int:payment_id>/receipt/", generate_receipt, name="download_receipt"),
    path('pay/<int:id>/', initiate_payment, name='payment'),
    path('registration/', payment_view, name='registration'),
    # path("export_pdf/", exportp_csv, name="export_pdf"),
    path("newofficial/", Official, name="add_official"),
    path("officials/", school_offs, name="officials"),
    path("allofficials/", all_officials, name="allofficials"),
    path('officials/update/<int:id>/', update_official, name='update_official'),
    path("official/<int:id>", OfficialDetail, name="official"),
    path("delete-official/<int:id>", DeleteOfficial, name="del_official"),
    path("activate_official/<int:id>", activate_official, name="activate_official"),
    path("deactivate_official/<int:id>", deactivate_official, name="deactivate_official"),
    # path("delete-official/<int:id>", DeleteOfficial, name="del_official"),
    # path("delete-official/<int:id>", DeleteOfficial, name="del_official"),
    path('payment/success/<str:transaction_id>/', payment_success, name='payment_success'),
    path('airtel/payment/callback/', airtel_payment_callback, name='airtel_payment_callback'),
    # path('payment/<uuid:transaction_id>/status/', payment_status, name='payment_status'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
