# Generated by Django 5.1.1 on 2024-11-08 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='trainee_photo/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('school', models.CharField(max_length=125)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=14)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainee_district', to='accounts.district')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainee_region', to='accounts.region')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainee_zone', to='accounts.zone')),
            ],
        ),
    ]
